### ISSUE TITLE
Webplayer issues with Unity 2017.2

### ISSUE THREAD

**Issue by rorywalsh** [aliessmael/Unity-Logs-Viewer#23]
Many thanks for this wonderful tool. Although I've been using using it for year without a problem, on import into the latest Unity build I get the following error: 
`Assets/Unity-Logs-Viewer/Reporter/Reporter.cs(2013,47): error CS0619: `UnityEngine.RuntimePlatform.OSXWebPlayer' is obsolete: `WebPlayer export is no longer supported in Unity 5.4+.'
`
Commenting out the offending code get me past the error, but when I open the log window I get a 'cannot connect to destination host' error. Any ideas?

**Comment by wenderRondonia** [comment]
you need to comment out only line 2013, lines 2014 and 2015 need to stay, it worked for me this way.

**Comment by rorywalsh** [comment]
Thanks. Hopefully that does the trick. Feel free to close this. I can
reopen if I have any further issues.

On 17 February 2018 at 15:01, Wender Alves Libório <notifications@github.com

**Comment by omundy** [comment]
Line 2013 still exists in the version on the asset store

![image](https://user-images.githubusercontent.com/279945/51795202-5fb0ec80-21ad-11e9-989e-f739440cc606.png)

**Comment by procw** [comment]
I have problem in 2018.4.30f1.
Logs: `Assets\Pro Standard Assets\Image Based\ColorCorrectionEffectPCMac_26.cs(20,9): error CS0619: 'RuntimePlatform.OSXWebPlayer' is obsolete: 'WebPlayer export is no longer supported in Unity 5.4+.'` 
How can I fix this?

**Comment by AbdulrahmanGhalib** [comment]
do you fix this error?

**Comment by rorywalsh** [comment]
Sorry, I never did. I started using JS frameworks for web stuff instead.
