### ISSUE TITLE
Critical errors when load scenes from AssetBundles

### ISSUE THREAD

**Issue by vSonne** [aliessmael/Unity-Logs-Viewer#28]
in Reporter.cs at 311 line:
`sample.loadedScene = (byte)SceneManager.GetActiveScene().buildIndex;`
If scene loaded from AssetBundle, buildIndex is equal `-1`, but `(byte)-1` is equal 255.

Then at 92 line:
```
if ((int)loadedScene == -1)
	return "AssetBundleScene";
```
the condition is not met and every frame in console write critical error.

**Comment by aliessmael** [comment]
fixed
