### ISSUE TITLE
Reporter Can't Handle AssetBundle Scenes

### ISSUE THREAD

**Issue by Oshroth** [aliessmael/Unity-Logs-Viewer#3]
Reporter will generate errors when loading scenes from Asset Bundles because they have a level index of -1 which causes an IndexOutOfRangeException when trying to access the scenes array.

````csharp
if( string.IsNullOrEmpty( scenes[ Application.loadedLevel ] ))
			scenes[ Application.loadedLevel ] = Application.loadedLevelName ;
````
Error: IndexOutOfRangeException: Array index is out of range.
Reporter.Update () (at Assets/Reporter/Reporter.cs:1817)

**Comment by aliessmael** [comment]
fixed
