### ISSUE TITLE
Update Asset Store Package to v1.7

### ISSUE THREAD

**Issue by jcs090218** [aliessmael/Unity-Logs-Viewer#31]
Hi, I realize if the warnings are all fixed and ready to release version 1.7, could you update the Log Viewer in Unity Asset Store? I tried to download the Log Viewer package yesterday but it seems like is still on version 1.6. Thank you!

**Comment by TCROC** [comment]
I agree with this.  It would be much appreciated.  That or have a releases section here on GitHub with the package (or both).

**Comment by jcs090218** [comment]
@TCROC I have released the package under my branch of repo [here](https://github.com/jcs-PR/Unity-Logs-Viewer/releases). Hopefully we can update the release v1.7 both on Unity Assets Store and on this repo once the author has get back to us. :(

**Comment by aliessmael** [comment]
Done, Waiting unity approval.

**Comment by jcs090218** [comment]
The version is update to date! I will close this issue for now.
