### ISSUE TITLE
DREAMMAKERSGROUP Log Viewer doesn't work the second time

### ISSUE THREAD

**Issue by JulianHSC** [aliessmael/Unity-Logs-Viewer#38]
I'm not sure if this post would even be read. I sent an e-mail to the unity technologies team.  See the e-mail below:

Your link in https://assetstore.unity.com/packages/tools/integration/log-viewer-12047 doesn't create a reporter object in my unity from the second time onwards. Check the screenshots i sent.  As I said, it DID  work the first time. Please reply this post if you don't understand anything.

Attachment(s)
reporter not working.JPG
reporter working.JPG
![Reporter not working 1](https://user-images.githubusercontent.com/31162511/64583700-85010c80-d3c4-11e9-88d1-81639ca93035.JPG)
![reporter working](https://user-images.githubusercontent.com/31162511/64583707-8a5e5700-d3c4-11e9-9189-67cabaf516fc.JPG)

**Comment by aliessmael** [comment]
Hi Julian.
I have tried a lot to reproduce same issue, but every thing is fine. Do you see any console error when Create Reporter?

However these images are filled using script ReporterEditor.cs at line 33
can you please put break point there and check if every thing is OK.

**Comment by JulianHSC** [comment]
Hello aliessmael,

There are absolutely no error messages of any kind. The issue is this: When the first project was created, I did NOT create the reporter object in the scene. That's the strange thing. In the second project I created, it just refused to appear. I think I already sent both screenshots to you and for the second case, the project just wasn't there. I also noticed that some build in some folder didn't appear in the second project. So tell me what is going on. If you want, i can send you both projects in a 7zip file so you can compare them yourself.


________________________________

**Comment by aliessmael** [comment]
It is not suppose to create buy it self.
Can you send me the project ?

**Comment by aliessmael** [comment]
The only way to make it create by itself is to put [InitializeOnLoadMethod] before CreateReporter method

**Comment by JulianHSC** [comment]
I'm not interested in the explanation. Check why it doesn't work.

I'm giving you the link because the file is too big.

Unity touch test  - Reporter working.

https://drive.google.com/file/d/1UBqikRJwC5b63SCVSDjErniSD97iKhcV/view?usp=sharing

Swipe input test - reporter not working.
https://drive.google.com/file/d/1B-clRJyq8mIM3HAq1hh54Dfi1Jtu8bqc/view?usp=sharing


________________________________

**Comment by aliessmael** [comment]
I just create 3 reporter for each project
All are filled correctly.

![image](https://user-images.githubusercontent.com/12550907/64662094-45840000-d458-11e9-8b97-da82d644b681.png)

![image](https://user-images.githubusercontent.com/12550907/64662140-677d8280-d458-11e9-8100-2e78d3465c8a.png)

![image](https://user-images.githubusercontent.com/12550907/64662168-7c5a1600-d458-11e9-99ba-6453f9919da4.png)

![image](https://user-images.githubusercontent.com/12550907/64662193-9136a980-d458-11e9-808e-751691a0fde9.png)

**Comment by JulianHSC** [comment]
Hello aliessmael,

Can you make sure that the previous e-mail / conversation is not removed? Why are you removing it? It makes it more difficult to follow what is happening. And can you give the steps how you manage to get the project and the inspector attributes filled? It's no use giving me a screenshot of what works when the steps are not there.

Note: I have tried to go to https://assetstore.unity.com/packages/tools/integration/log-viewer-12047 directly from the unity editor and so far it only works ONCE.

Where do you go to? show the steps.

________________________________

**Comment by aliessmael** [comment]
I did not remove any conversation, I just did misspelling fix for one of the messages "instead of buy i make it by"
I am right now at work, So i will give quick steps

go to unity store -> download and import the package. then go to menu Reporter -> Create

**Comment by aliessmael** [comment]
Is your issue fixed?
