### ISSUE TITLE
Incorrect Line

### ISSUE THREAD

**Issue by ljarasunas2021** [aliessmael/Unity-Logs-Viewer#46]
<img width="610" alt="Screen Shot 2020-03-25 at 6 49 55 PM" src="https://user-images.githubusercontent.com/43383815/77602189-0c7a1d00-6eca-11ea-97d1-883d65001150.png">
I can't seem to find the correct line number.  The correct line numbers are shown in unity's console but not this console. Is there any way to either get the correct linenumbers or somehow interpret these incorrect line numbers?

Thank you! Great asset btw otherwise!

**Comment by aliessmael** [comment]
Try to enable development in build settings you will get better information

**Comment by ljarasunas2021** [comment]
Yup that did it thank you so much! Great asset btw! I was having this issue that only occurred in a built version of the game and not in the unity editor and was prepared to right a ton of code just to figure out what was wrong, but this allowed me to find the errors within the game quite easily.  Thank you so much!
