### ISSUE TITLE
ReporterGUI.cs

### ISSUE THREAD

**Issue by gresolio** [aliessmael/Unity-Logs-Viewer#9]
What is the main purpose of the "ReporterGUI.cs"? Currently it's a dummy script, which just calls reporter.OnGUIDraw() and nothing more. Do you plan refactoring? (maybe move all GUI-related stuff from "Reporter.cs" to this "ReporterGUI.cs")

Because without refactoring it makes no sense to keep this dummy script. It brings only "add/destroy component" extra effort to show/hide the Reporter. Please explain, why one needs to do so? Currently it is easier to just use OnGUI() inside "Reporter.cs", or are there some special cases?

p.s. I've decided to add "disable Reporter in Editor" bool variable, and then faced this interesting show/hide logic via "ReporterGUI.cs", so the question appeared.

**Comment by aliessmael** [comment]
To enable disable drawing you have to remove add "ReporterGUI.cs", The reason I did it like this to be able enable disable the whole OnGUI method on run time, because OnGUI takes performance even it is empty, by removing "ReporterGUI.cs" no OnGUI even empty,
Before I did whole drawing in "ReporterGUI.cs" but I had to make members as public and many other issue

**Comment by gresolio** [comment]
Thanks, now I understand. One more question:
Did you perform some real measurements, and what impact on performance did you see?

It's very interesting topic for me. I've read recently [10000 UPDATE() CALLS](http://blogs.unity3d.com/2015/12/23/1k-update-calls/), and this great article has shed some light on Unity scripting internals, also there is a small [example project](https://github.com/valyard/Unity-Updates). Of course even empty method does affect performance. But this impact is only noticeable if you have thousands of such methods.

**Comment by aliessmael** [comment]
I am sorry for being late i forget to answer you,
you can easily find the problem of empty OnGUI from profiler window of unity.
Create new project with one script without onGUI and have look at profiler, then create empty OnGUI and check profiler again you will find GUI.Repaint ,check images below, I didnot read any performance articles I just notice it on profiler.

![aa](https://cloud.githubusercontent.com/assets/12550907/14829146/1733a544-0bfb-11e6-8ec5-49648ccbe6e3.png)

![untitled](https://cloud.githubusercontent.com/assets/12550907/14829161/2960ee48-0bfb-11e6-8369-7897f57c18ca.png)
